name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub (if needed)
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push backend Docker image (if applicable)
        working-directory: ./backend
        run: |
          docker build -t sumanreddy568/bmi_calculator_backend .
          docker push sumanreddy568/bmi_calculator_backend

      - name: Build and push frontend Docker image (if applicable)
        working-directory: ./frontend
        run: |
          docker build -t sumanreddy568/bmi_calculator_frontend .
          docker push sumanreddy568/bmi_calculator_frontend

      - name: SSH Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd /home/adcadmin/dumy-path
            if [ -d "BMI_Calculator" ]; then
              cd BMI_Calculator
              git pull
            else
              git clone https://github.com/SumanReddy568/BMI_Calculator.git
              cd BMI_Calculator
            fi
            docker-compose pull
            docker-compose up -d --remove-orphans
