name: Deploy to Server

on:
  push:
    branches:
      - main  # Trigger on push to main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push backend Docker image
        working-directory: ./backend
        run: |
          docker build -t sumanreddy568/bmi_calculator_backend .
          docker push sumanreddy568/bmi_calculator_backend

      - name: Build and push frontend Docker image
        working-directory: ./frontend
        run: |
          docker build -t sumanreddy568/bmi_calculator_frontend .
          docker push sumanreddy568/bmi_calculator_frontend

      - name: SSH Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}  # Optional, default is 22
          script: |
            cd /home/adcadmin/Music  # Navigate to the directory containing docker-compose.yml
            git pull origin main  # Pull the latest changes from Git
            docker-compose pull  # Pull updated images
            docker-compose up -d --remove-orphans  # Recreate containers
